In [1]:
import pandas as pd
import sys
pd.set_option('display.max_rows', None)

In [12]:
import os
sys.path.append(os.path.join(os.getcwd(), "../common"))
import yaml

In [27]:
with open(os.path.join(os.getcwd(), "../common/IndustryTop.yaml"), 'r', encoding='utf-8') as f:
    data = yaml.safe_load(f)

In [25]:
data['detail'].keys

In [28]:
data['detail']

{'家电': {1: '美的集团', 2: '格力电器', 3: '老板电器'},
 '通用机械头': {4: '恒立液压', 5: '艾迪精密', 6: '中航重机'},
 '锂电池': {7: '天际股份', 8: '融捷股份', 9: '宁德时代'},
 '纸': {10: '冠豪高斯', 11: '仙鹤股份', 12: '太阳纸业'},
 '饮料': {13: '泉阳泉', 14: '养元饮品', 15: '承德露露'},
 '食用油': {16: '金龙鱼', 17: '道道全', 18: '京粮控股'},
 '火腿': {19: '双汇发展', 20: '上海梅林', 21: '得利斯'},
 '券商': {22: '招商证券', 23: '兴业证券', 24: '东方财富'},
 '保险': {25: '中国平安', 26: '中国人寿', 27: '新华保险'},
 '银行': {28: '平安银行', 29: '招商银行', 30: '兴业银行'},
 '地产': {31: '合肥城建', 32: '苏宁环球', 33: '万科A'},
 '光伏': {34: '隆基股份', 35: '阳光电源', 36: '通威股份'},
 '眼科': {37: '爱尔眼科', 38: '金城医药', 39: '丰原药业'},
 '牙科': {40: '通策医疗'},
 '苹果概念': {41: '歌尔股份', 42: '立讯精密', 43: '德赛电池'},
 '酱油': {44: '海天味业', 45: '千禾味业'},
 '白酒': {46: '贵州茅台', 47: '五粮液', 48: '泸州老窖'},
 '牛奶': {49: '伊利股份', 50: '新乳业', 51: '三元股份'},
 '猪肉': {52: '牧原股份', 53: '新希望', 54: '新五丰'},
 '疫苗': {55: '智飞生物', 56: '博野生物', 57: '复星医药'},
 '激素': ['智飞生物', '博野生物', '复星医药'],
 '医药': ['恒瑞医药', '丽珠集团', '新和成'],
 '防水': ['东方雨虹', '科顺股份', '凯伦股份'],
 '快递': ['广汇物流', '东方嘉盛', '顺丰控股'],
 '化工': ['万华化学', '恒力石化', '鲁西化工'],
 '电力': ['长江电力', '天富能源', '上海电力'],
 '新能源车': ['比亚迪', '小康股份', '长安汽车'],
 '人工智能': ['海康威视', '中科曙光', '科大讯飞'],
 '机械': ['三一重工', '中联重科', '徐卫机械'],
 '数字货币': ['御银股份', '京北方', '银之杰'],
 '半导体': ['国科微', '汇顶科技', '韦尔股份'],
 '黄金': ['紫金矿业', '中国黄金', '赤峰黄金'],
 '免税': ['中国中免', '王府井', '凯撒旅业'],
 '煤炭': ['潞安环能', '郑州煤电', '陕西黑猫'],
 '水泥': ['上峰水泥', '海螺水泥', '四川双马'],
 '空调': ['格力电器', '美的电器', '海尔智家'],
 '面板': ['TCL科技', '京东方A', '彩虹股份'],
 '支架': ['乐普医疗', '信立泰', '蓝帆医疗'],
 '精装修': ['中天精装', '金螳螂', '海鸥住工'],
 '钴': ['章源钨业', '格林美', '华友钴业'],
 '种子': ['丰乐种业', '农发种业'],
 '中药': ['云南白药', '片仔癀', '广誉远', '葵花药业'],
 '榨菜': ['涪陵榨菜'],
 '火锅底料': ['安井食品', '惠发食品', '三全食品'],
 'pve手套': ['英科医疗', '蓝帆医疗', '鱼跃医疗'],
 '元宇宙': ['中青宝', '湖北广电'],
 '封测': ['长电科技', '品方科技'],
 '稀土': ['盛和资源', '北方稀土', '五矿稀土'],
 '汽配': ['福耀玻璃', '华域汽车', '江特电机'],
 '痔疮': ['马应龙'],
 '饲料': ['傲农生物', '大北农', '天邦股份'],
 '机场': ['中国国航', '白云机场', '春秋航空'],
 '电影院': ['万达电影', '幸福蓝海', '金逸影视'],
 '旅游': ['桂林旅游', '西安旅游', '天目湖'],
 '地板': ['大亚圣象', '兔宝宝'],
 '传媒': ['中国出版', '分众传媒', '欢瑞世纪'],
 '手机游戏': ['游族网络', '完美世界', '金科文化'],
 '钢铁': ['重庆钢铁', '太钢不锈', '八一钢铁'],
 '化学纤维': ['恒力石化', '荣盛石化', '新凤鸣'],
 '瓷砖': ['蒙娜丽莎', '东鹏控股'],
 '插座': ['公牛集团', '白云电器'],
 '安防': ['海康威视', '大华股份', '安居宝'],
 '硅': ['三友化工', '兴发集团', '合盛硅业'],
 '床垫': ['喜临门', '梦百合', '熊盛科技'],
 '公路': ['四川成渝', '招商公路', '广深铁路'],
 '集装箱': ['中集集团'],
 '航运': ['中远海控', '中远海发', '宁波海运'],
 '染料': ['七彩化学', '江苏吴中', '浙江龙成'],
 '丝袜': ['浪莎股份', '汇洁股份', '龙头股份'],
 '风电': ['特变电工', '天顺风能', '金风科技'],
 '电动车': ['新日股份', '永安行'],
 '酒店餐饮': ['华天酒店', '西安饮食', '锦江酒店'],
 '辅助生殖': ['景峰医药', '国药现代'],
 '电源设备': ['阳光电源', '中来股份', '通威股份'],
 '啤酒': ['重庆啤酒', '青岛啤酒', '珠江啤酒'],
 '保健品': ['汤臣倍健', '同仁堂', '仙乐健康'],
 '鸿蒙系统': ['润和软件', '拓维信息', '国民技术'],
 '衣柜': ['志邦家居', '索菲亚', '皮阿诺'],
 '化妆品': ['上海家化', '珀莱雅', '丽人丽妆'],
 '钛白粉': ['龙蟒佰利', '金浦钛业', '中核钛白'],
 '醋': ['恒顺醋业', '莲花健康', '中炬高新'],
 '胎压监测': ['华阳集团'],
 '教育': ['开元教育', '海伦钢琴', '中公教育'],
 '医美': ['华东医药', '长江健康'],
 '养老概念': ['珠江股份', '奥佳华', '宜华健康'],
 '国防军工': ['新余国科', '北方导航', '三角防务'],
 '通信设备': ['光库科技', '瑞斯康达', '吉大通信'],
 '碳中和': ['中材节能', '开尔新材', '长源电力'],
 '光伏建筑一体化': ['华自科技', '启迪设计'],
 '可降解塑料': ['金发科技', '华信新社', '美联新材'],
 '碳捕获': ['凯美特气', '远达环保', '杭氧股份'],
 '环保工程': ['久吾高科', '中环环保'],
 '涂料龙头': ['兔宝宝', '坤彩科技'],
 '草铵膦': ['科尔化学', '兴发集团'],
 'MCU芯片': ['国民技术', '富满电子', '士兰微'],
 '半导体材料': ['阿石创', '飞凯材料', '南大光电'],
 '芯片半导体': ['国科微', '中芯国际', '兆易创新']}

In [14]:
data

{'version': '0.0.1',
 'detail': [{'行业1': [{202223: '广发'}, {202213: '飞发'}]},
  {'行业2': [{202222: '广发分'}]}],
 'ego_ver': '0.4.7',
 'round': [{'A': {'is_back_propagate_embeddings': False,
    'is_back_propagate_params': False}},
  {'is_back_propagate_embeddings': False},
  {'is_back_propagate_embeddings': True, 'is_back_propagate_params': True}],
 'sparse_plugin': {'adf_decay_rate': 0.999,
  'emb_inputs_info': [{'dim': 2205,
    'folded': False,
    'name': 'all_slots',
    'slot_categories': '1001 2001 2004 2006 2009 2010 2011 2101 2102 2103 2301 2302 2303 2401 2402 2403 3001 4006 4007 4008 4009 5002 5003 5004 5005 5007 5008 5010 5051 5060 6007 6008 6017 6018 6027 6045 6048 6145 6148 6245 21014 21015 21016 21017 21024 21025 21026 21027 21034 21035 21036 21037 21044 21045 21046 21047 21114 21115 21116 21117 21224 21225 21226 21227 21234 21235 21236 21237 22014 22015 22016 22017 22024 22025 22026 22027 22034 22035 22036 22037 22044 22045 22046 22047 22114 22115 22116 22117 22234 22235 22236 22237 23016 23017 23024 23026 23027 23036 23037 23044 23046 23047 23114 23116 23117',
    'use_nsc': False}],
  'inputs_info': [{'dim': 72,
    'folded': False,
    'name': 'dense',
    'use_nsc': False},
   {'dim': 56, 'folded': False, 'name': 'onehot', 'use_nsc': False}],
  'slot_category_info': [{'dim': 21,
    'slot_category': '1001 2001 2004 2006 2009 2010 2011 2101 2102 2103 2301 2302 2303 2401 2402 2403 3001 4006 4007 4008 4009 5002 5003 5004 5005 5007 5008 5010 5051 5060 6007 6008 6017 6018 6027 6045 6048 6145 6148 6245 21014 21015 21016 21017 21024 21025 21026 21027 21034 21035 21036 21037 21044 21045 21046 21047 21114 21115 21116 21117 21224 21225 21226 21227 21234 21235 21236 21237 22014 22015 22016 22017 22024 22025 22026 22027 22034 22035 22036 22037 22044 22045 22046 22047 22114 22115 22116 22117 22234 22235 22236 22237 23016 23017 23024 23026 23027 23036 23037 23044 23046 23047 23114 23116 23117'}]},
 'targets': [{'assign_op': 'group_deps',
   'emb_grads': [{'grad_name': 'gradients/AddN_5:0',
     'var_name': 'all_slots:0'}],
   'emb_inputs': 'all_slots:0',
   'inputs': 'dense:0 onehot:0',
   'label': 'label_0_0:0',
   'label_name': 'label_0_0',
   'loss': 'add_3:0',
   'loss_weight': 'loss_weight0:0',
   'norm_nodes': [{'input': 'DenseTower_0/input_norm/concat_4:0',
     'mean': 'DenseTower_0/input_norm/mean:0',
     'var': 'DenseTower_0/input_norm/var:0'}],
   'output': 'p0_click:0',
   'param_grads': [{'grad_name': 'gradients/DenseTower_0/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_0/layer_1/kernel:0'},
    {'grad_name': 'gradients/DenseTower_0/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_0/layer_1/bias:0'},
    {'grad_name': 'gradients/DenseTower_0/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_0/layer_2/kernel:0'},
    {'grad_name': 'gradients/DenseTower_0/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_0/layer_2/bias:0'},
    {'grad_name': 'gradients/p0_click/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_click/layer_1/kernel:0'},
    {'grad_name': 'gradients/p0_click/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_click/layer_1/bias:0'},
    {'grad_name': 'gradients/p0_click/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_click/layer_2/kernel:0'},
    {'grad_name': 'gradients/p0_click/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_click/layer_2/bias:0'},
    {'grad_name': 'gradients/p0_atc/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_atc/layer_1/kernel:0'},
    {'grad_name': 'gradients/p0_atc/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_atc/layer_1/bias:0'},
    {'grad_name': 'gradients/p0_atc/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_atc/layer_2/kernel:0'},
    {'grad_name': 'gradients/p0_atc/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_atc/layer_2/bias:0'},
    {'grad_name': 'gradients/p0_order/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_order/layer_1/kernel:0'},
    {'grad_name': 'gradients/p0_order/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_order/layer_1/bias:0'},
    {'grad_name': 'gradients/p0_order/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_order/layer_2/kernel:0'},
    {'grad_name': 'gradients/p0_order/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_order/layer_2/bias:0'}],
   'print_histo_vars_to_tensorboard': '',
   'print_scalar_vars_to_tensorboard': '',
   'print_vars_to_hdfs': '',
   'print_vars_to_log': '',
   'target_name': 'p0_click'},
  {'assign_op': 'group_deps',
   'emb_grads': [{'grad_name': 'gradients/AddN_5:0',
     'var_name': 'all_slots:0'}],
   'emb_inputs': 'all_slots:0',
   'inputs': 'dense:0 onehot:0',
   'label': 'label_0_2:0',
   'label_name': 'label_0_2',
   'loss': 'add_6:0',
   'loss_weight': 'loss_weight1:0',
   'norm_nodes': [{'input': 'DenseTower_0/input_norm/concat_4:0',
     'mean': 'DenseTower_0/input_norm/mean:0',
     'var': 'DenseTower_0/input_norm/var:0'}],
   'output': 'p0_atc:0',
   'param_grads': [{'grad_name': 'gradients/DenseTower_0/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_0/layer_1/kernel:0'},
    {'grad_name': 'gradients/DenseTower_0/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_0/layer_1/bias:0'},
    {'grad_name': 'gradients/DenseTower_0/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_0/layer_2/kernel:0'},
    {'grad_name': 'gradients/DenseTower_0/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_0/layer_2/bias:0'},
    {'grad_name': 'gradients/p0_click/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_click/layer_1/kernel:0'},
    {'grad_name': 'gradients/p0_click/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_click/layer_1/bias:0'},
    {'grad_name': 'gradients/p0_click/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_click/layer_2/kernel:0'},
    {'grad_name': 'gradients/p0_click/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_click/layer_2/bias:0'},
    {'grad_name': 'gradients/p0_atc/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_atc/layer_1/kernel:0'},
    {'grad_name': 'gradients/p0_atc/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_atc/layer_1/bias:0'},
    {'grad_name': 'gradients/p0_atc/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_atc/layer_2/kernel:0'},
    {'grad_name': 'gradients/p0_atc/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_atc/layer_2/bias:0'},
    {'grad_name': 'gradients/p0_order/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_order/layer_1/kernel:0'},
    {'grad_name': 'gradients/p0_order/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_order/layer_1/bias:0'},
    {'grad_name': 'gradients/p0_order/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_order/layer_2/kernel:0'},
    {'grad_name': 'gradients/p0_order/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_order/layer_2/bias:0'}],
   'print_histo_vars_to_tensorboard': '',
   'print_scalar_vars_to_tensorboard': '',
   'print_vars_to_hdfs': '',
   'print_vars_to_log': '',
   'target_name': 'p0_atc'},
  {'assign_op': 'group_deps',
   'emb_grads': [{'grad_name': 'gradients/AddN_5:0',
     'var_name': 'all_slots:0'}],
   'emb_inputs': 'all_slots:0',
   'inputs': 'dense:0 onehot:0',
   'label': 'label_0_4:0',
   'label_name': 'label_0_4',
   'loss': 'add_9:0',
   'loss_weight': 'loss_weight2:0',
   'norm_nodes': [{'input': 'DenseTower_0/input_norm/concat_4:0',
     'mean': 'DenseTower_0/input_norm/mean:0',
     'var': 'DenseTower_0/input_norm/var:0'}],
   'output': 'p0_order:0',
   'param_grads': [{'grad_name': 'gradients/DenseTower_0/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_0/layer_1/kernel:0'},
    {'grad_name': 'gradients/DenseTower_0/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_0/layer_1/bias:0'},
    {'grad_name': 'gradients/DenseTower_0/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_0/layer_2/kernel:0'},
    {'grad_name': 'gradients/DenseTower_0/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_0/layer_2/bias:0'},
    {'grad_name': 'gradients/p0_click/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_click/layer_1/kernel:0'},
    {'grad_name': 'gradients/p0_click/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_click/layer_1/bias:0'},
    {'grad_name': 'gradients/p0_click/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_click/layer_2/kernel:0'},
    {'grad_name': 'gradients/p0_click/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_click/layer_2/bias:0'},
    {'grad_name': 'gradients/p0_atc/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_atc/layer_1/kernel:0'},
    {'grad_name': 'gradients/p0_atc/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_atc/layer_1/bias:0'},
    {'grad_name': 'gradients/p0_atc/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_atc/layer_2/kernel:0'},
    {'grad_name': 'gradients/p0_atc/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_atc/layer_2/bias:0'},
    {'grad_name': 'gradients/p0_order/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_order/layer_1/kernel:0'},
    {'grad_name': 'gradients/p0_order/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_order/layer_1/bias:0'},
    {'grad_name': 'gradients/p0_order/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p0_order/layer_2/kernel:0'},
    {'grad_name': 'gradients/p0_order/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p0_order/layer_2/bias:0'}],
   'print_histo_vars_to_tensorboard': '',
   'print_scalar_vars_to_tensorboard': '',
   'print_vars_to_hdfs': '',
   'print_vars_to_log': '',
   'target_name': 'p0_order'},
  {'assign_op': 'group_deps_1',
   'emb_grads': [{'grad_name': 'gradients_1/AddN_5:0',
     'var_name': 'all_slots:0'}],
   'emb_inputs': 'all_slots:0',
   'inputs': '',
   'label': 'label_1_0:0',
   'label_name': 'label_1_0',
   'loss': 'add_12:0',
   'loss_weight': 'loss_weight3:0',
   'norm_nodes': [{'input': 'DenseTower_1/input_norm/Reshape_3:0',
     'mean': 'DenseTower_1/input_norm/mean:0',
     'var': 'DenseTower_1/input_norm/var:0'}],
   'output': 'p1_click:0',
   'param_grads': [{'grad_name': 'gradients_1/DenseTower_1/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_1/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/DenseTower_1/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_1/layer_1/bias:0'},
    {'grad_name': 'gradients_1/DenseTower_1/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_1/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/DenseTower_1/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_1/layer_2/bias:0'},
    {'grad_name': 'gradients_1/p1_click/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_click/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/p1_click/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_click/layer_1/bias:0'},
    {'grad_name': 'gradients_1/p1_click/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_click/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/p1_click/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_click/layer_2/bias:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_atc/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_atc/layer_1/bias:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_atc/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_atc/layer_2/bias:0'},
    {'grad_name': 'gradients_1/p1_order/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_order/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/p1_order/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_order/layer_1/bias:0'},
    {'grad_name': 'gradients_1/p1_order/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_order/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/p1_order/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_order/layer_2/bias:0'}],
   'print_histo_vars_to_tensorboard': '',
   'print_scalar_vars_to_tensorboard': '',
   'print_vars_to_hdfs': '',
   'print_vars_to_log': '',
   'target_name': 'p1_click'},
  {'assign_op': 'group_deps_1',
   'emb_grads': [{'grad_name': 'gradients_1/AddN_5:0',
     'var_name': 'all_slots:0'}],
   'emb_inputs': 'all_slots:0',
   'inputs': '',
   'label': 'label_1_2:0',
   'label_name': 'label_1_2',
   'loss': 'add_15:0',
   'loss_weight': 'loss_weight4:0',
   'norm_nodes': [{'input': 'DenseTower_1/input_norm/Reshape_3:0',
     'mean': 'DenseTower_1/input_norm/mean:0',
     'var': 'DenseTower_1/input_norm/var:0'}],
   'output': 'p1_atc:0',
   'param_grads': [{'grad_name': 'gradients_1/DenseTower_1/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_1/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/DenseTower_1/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_1/layer_1/bias:0'},
    {'grad_name': 'gradients_1/DenseTower_1/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_1/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/DenseTower_1/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_1/layer_2/bias:0'},
    {'grad_name': 'gradients_1/p1_click/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_click/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/p1_click/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_click/layer_1/bias:0'},
    {'grad_name': 'gradients_1/p1_click/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_click/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/p1_click/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_click/layer_2/bias:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_atc/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_atc/layer_1/bias:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_atc/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_atc/layer_2/bias:0'},
    {'grad_name': 'gradients_1/p1_order/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_order/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/p1_order/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_order/layer_1/bias:0'},
    {'grad_name': 'gradients_1/p1_order/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_order/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/p1_order/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_order/layer_2/bias:0'}],
   'print_histo_vars_to_tensorboard': '',
   'print_scalar_vars_to_tensorboard': '',
   'print_vars_to_hdfs': '',
   'print_vars_to_log': '',
   'target_name': 'p1_atc'},
  {'assign_op': 'group_deps_1',
   'emb_grads': [{'grad_name': 'gradients_1/AddN_5:0',
     'var_name': 'all_slots:0'}],
   'emb_inputs': 'all_slots:0',
   'inputs': '',
   'label': 'label_1_4:0',
   'label_name': 'label_1_4',
   'loss': 'add_18:0',
   'loss_weight': 'loss_weight5:0',
   'norm_nodes': [{'input': 'DenseTower_1/input_norm/Reshape_3:0',
     'mean': 'DenseTower_1/input_norm/mean:0',
     'var': 'DenseTower_1/input_norm/var:0'}],
   'output': 'p1_order:0',
   'param_grads': [{'grad_name': 'gradients_1/DenseTower_1/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_1/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/DenseTower_1/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_1/layer_1/bias:0'},
    {'grad_name': 'gradients_1/DenseTower_1/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'DenseTower_1/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/DenseTower_1/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'DenseTower_1/layer_2/bias:0'},
    {'grad_name': 'gradients_1/p1_click/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_click/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/p1_click/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_click/layer_1/bias:0'},
    {'grad_name': 'gradients_1/p1_click/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_click/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/p1_click/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_click/layer_2/bias:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_atc/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_atc/layer_1/bias:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_atc/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/p1_atc/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_atc/layer_2/bias:0'},
    {'grad_name': 'gradients_1/p1_order/layer_1/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_order/layer_1/kernel:0'},
    {'grad_name': 'gradients_1/p1_order/layer_1/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_order/layer_1/bias:0'},
    {'grad_name': 'gradients_1/p1_order/layer_2/matmul_kernel_grad/MatMul_1:0',
     'var_name': 'p1_order/layer_2/kernel:0'},
    {'grad_name': 'gradients_1/p1_order/layer_2/add_bias_grad/Reshape_1:0',
     'var_name': 'p1_order/layer_2/bias:0'}],
   'print_histo_vars_to_tensorboard': '',
   'print_scalar_vars_to_tensorboard': '',
   'print_vars_to_hdfs': '',
   'print_vars_to_log': '',
   'target_name': 'p1_order'},
  {'assign_op': 'group_deps_2',
   'emb_grads': [{'grad_name': '', 'var_name': 'all_slots:0'}],
   'emb_inputs': 'all_slots:0',
   'inputs': 'dense:0 onehot:0',
   'label': 'tlabel:0',
   'label_name': 'tlabel',
   'loss': '',
   'loss_weight': '',
   'norm_nodes': [{'input': 'DenseTower_0/input_norm/concat_4:0',
     'mean': 'DenseTower_0/input_norm/mean:0',
     'var': 'DenseTower_0/input_norm/var:0'}],
   'output': 'predict_node:0',
   'param_grads': [{'grad_name': '',
     'var_name': 'DenseTower_0/layer_1/kernel:0'},
    {'grad_name': '', 'var_name': 'DenseTower_0/layer_1/bias:0'},
    {'grad_name': '', 'var_name': 'DenseTower_0/layer_2/kernel:0'},
    {'grad_name': '', 'var_name': 'DenseTower_0/layer_2/bias:0'},
    {'grad_name': '', 'var_name': 'p0_click/layer_1/kernel:0'},
    {'grad_name': '', 'var_name': 'p0_click/layer_1/bias:0'},
    {'grad_name': '', 'var_name': 'p0_click/layer_2/kernel:0'},
    {'grad_name': '', 'var_name': 'p0_click/layer_2/bias:0'},
    {'grad_name': '', 'var_name': 'p0_atc/layer_1/kernel:0'},
    {'grad_name': '', 'var_name': 'p0_atc/layer_1/bias:0'},
    {'grad_name': '', 'var_name': 'p0_atc/layer_2/kernel:0'},
    {'grad_name': '', 'var_name': 'p0_atc/layer_2/bias:0'},
    {'grad_name': '', 'var_name': 'p0_order/layer_1/kernel:0'},
    {'grad_name': '', 'var_name': 'p0_order/layer_1/bias:0'},
    {'grad_name': '', 'var_name': 'p0_order/layer_2/kernel:0'},
    {'grad_name': '', 'var_name': 'p0_order/layer_2/bias:0'}],
   'print_histo_vars_to_tensorboard': '',
   'print_scalar_vars_to_tensorboard': '',
   'print_vars_to_hdfs': '',
   'print_vars_to_log': '',
   'target_name': 'predict_node'}],
 'validate_targets': ''}

In [2]:
DOWN_LOAD_PATH = "/Users/qingbin.zhuang/Downloads"

In [3]:
file = "day3_20221220-145733.csv"

In [4]:
df = pd.read_csv(f'{DOWN_LOAD_PATH}/{file}')

In [5]:
df.head(3)

           dt  hour  click_per     cnt
0  2022-12-17     0   0.000000  451113
1  2022-12-17     0   0.047619       1
2  2022-12-17     0   0.050000       1

In [6]:

sys.version_info, sys.maxsize

(sys.version_info(major=3, minor=9, micro=15, releaselevel='final', serial=0),
 9223372036854775807)

In [7]:
df[df['click_per']>0.5].cnt.sum()

24468

In [8]:
def agg_func(df):
    no_click = df[df['click_per']==0].cnt.sum()
    click_eq_imp = df[df['click_per']==0.5].cnt.sum()
    click_lt_imp = df[(df['click_per']<0.5) & (df['click_per'] != 0)].cnt.sum()
    all_cnt = df.cnt.sum()
    return pd.Series([no_click * 1.0 / all_cnt, click_eq_imp * 1.0 / all_cnt,
                click_lt_imp * 1.0 / all_cnt], ['no_click_percent', 'click_eq_imp_percent', 'click_lt_imp_percent'])

In [11]:
df.groupby(['dt', 'hour']).apply(agg_func).reset_index()

,dt,hour,no_click_percent,click_eq_imp_percent,click_lt_imp_percent
0,2022-12-17,0,0.957377,0.012211,0.029417
1,2022-12-17,1,0.955153,0.012610,0.031192
2,2022-12-17,2,0.956088,0.013308,0.029538
3,2022-12-17,3,0.956570,0.013273,0.029160
4,2022-12-17,4,0.957251,0.011333,0.030176
5,2022-12-17,5,0.958125,0.011125,0.029792
6,2022-12-17,6,0.955337,0.011132,0.032853
7,2022-12-17,7,0.956874,0.010449,0.032113
8,2022-12-17,8,0.957260,0.011330,0.030735
9,2022-12-17,9,0.957789,0.011534,0.029871
10,2022-12-17,10,0.957947,0.011816,0.029366
11,2022-12-17,11,0.959687,0.011746,0.027757
12,2022-12-17,12,0.959585,0.011679,0.027823
13,2022-12-17,13,0.957898,0.011604,0.029555
14,2022-12-17,14,0.959028,0.011464,0.028657
15,2022-12-17,15,0.959910,0.011648,0.027541
16,2022-12-17,16,0.960393,0.011265,0.027539
17,2022-12-17,17,0.958640,0.011270,0.029230
18,2022-12-17,18,0.959009,0.011851,0.028357
19,2022-12-17,19,0.959367,0.010891,0.028969
20,2022-12-17,20,0.958169,0.011114,0.029839
21,2022-12-17,21,0.957760,0.011183,0.030248
22,2022-12-17,22,0.957296,0.011744,0.029946
23,2022-12-17,23,0.955807,0.012281,0.030965
24,2022-12-18,0,0.955248,0.012656,0.031038
25,2022-12-18,1,0.955679,0.012692,0.030718
26,2022-12-18,2,0.956530,0.012732,0.029782
27,2022-12-18,3,0.952545,0.013883,0.032244
28,2022-12-18,4,0.954835,0.012410,0.031773
29,2022-12-18,5,0.957433,0.011770,0.029856
30,2022-12-18,6,0.957476,0.010886,0.031103
31,2022-12-18,7,0.954787,0.010245,0.034305
32,2022-12-18,8,0.956375,0.010898,0.031992
33,2022-12-18,9,0.956771,0.011052,0.031288
34,2022-12-18,10,0.958514,0.011390,0.029224
35,2022-12-18,11,0.957176,0.011889,0.029820
36,2022-12-18,12,0.957938,0.011048,0.030064
37,2022-12-18,13,0.958797,0.011057,0.029309
38,2022-12-18,14,0.959833,0.011250,0.028052
39,2022-12-18,15,0.960632,0.010640,0.027812
40,2022-12-18,16,0.959270,0.011333,0.028552
41,2022-12-18,17,0.959961,0.011304,0.027940
42,2022-12-18,18,0.959506,0.011073,0.028498
43,2022-12-18,19,0.959902,0.011187,0.028050
44,2022-12-18,20,0.959825,0.010942,0.028376
45,2022-12-18,21,0.958848,0.011356,0.028996
46,2022-12-18,22,0.958237,0.010929,0.029953
47,2022-12-18,23,0.955469,0.012377,0.031098
48,2022-12-19,0,0.954170,0.012711,0.031976
49,2022-12-19,1,0.954390,0.013418,0.030809
50,2022-12-19,2,0.954652,0.013022,0.031364
51,2022-12-19,3,0.956215,0.013024,0.029686
52,2022-12-19,4,0.961699,0.011577,0.025733
53,2022-12-19,5,0.959020,0.011513,0.028642
54,2022-12-19,6,0.959395,0.011100,0.028934
55,2022-12-19,7,0.956993,0.010830,0.031575
56,2022-12-19,8,0.960995,0.010372,0.028011
57,2022-12-19,9,0.960159,0.010917,0.028189
58,2022-12-19,10,0.962487,0.010840,0.025997
59,2022-12-19,11,0.962203,0.011392,0.025617
60,2022-12-19,12,0.960527,0.011427,0.027235
61,2022-12-19,13,0.961201,0.011243,0.026757
62,2022-12-19,14,0.962220,0.011201,0.025643
63,2022-12-19,15,0.962111,0.011286,0.025855
64,2022-12-19,16,0.962748,0.011338,0.024993
65,2022-12-19,17,0.962297,0.010979,0.025880
66,2022-12-19,18,0.962493,0.010815,0.025804
67,2022-12-19,19,0.959563,0.011540,0.027957
68,2022-12-19,20,0.959371,0.011408,0.028386
69,2022-12-19,21,0.959798,0.010921,0.028504
70,2022-12-19,22,0.957815,0.011531,0.029879
71,2022-12-19,23,0.956503,0.011973,0.030641
72,2022-12-20,0,0.956042,0.012278,0.030733
73,2022-12-20,1,0.954927,0.013233,0.030758
74,2022-12-20,2,0.952837,0.013964,0.031881
75,2022-12-20,3,0.955839,0.013760,0.029052
76,2022-12-20,4,0.956920,0.011939,0.030004
77,2022-12-20,5,0.958162,0.010980,0.030228
78,2022-12-20,6,0.957324,0.010440,0.031790
79,2022-12-20,7,0.959314,0.010363,0.029741
80,2022-12-20,8,0.959752,0.011459,0.028059

In [12]:
df.groupby(['dt', 'hour']).apply(agg_func).reset_index().to_csv("tmp.csv")