In [1]:
import sys
import os
import akshare as ak
from datetime import date, datetime
# 获取当前文件所在目录（B 文件夹），再上移一级变成 project/
current_dir = os.path.dirname(os.path.abspath("__file__"))
project_root = os.path.abspath(os.path.join(current_dir, '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from DataFetch.stock_basic import *
import pandas as pd
from sqlalchemy import create_engine
from common.utils import get_engine, code_add_suffix
import time
from plotly.subplots import make_subplots
engine = get_engine()

In [2]:
query = f"""
SELECT * FROM daily_kline
WHERE trade_date >= '2025-01-01' AND trade_date <= '2025-05-29'
ORDER BY trade_date DESC
"""
df = pd.read_sql(query, engine)

In [ ]:
import akshare as ak

data_lst = []
for ts_code in df.ts_code:
    if ts_code.endswith("BJ"):
        continue
    try:
        data_tmp = ak.stock_comment_detail_scrd_focus_em(symbol=ts_code.split(".")[0])
        data_tmp.columns = ["trade_date", "follow_user_cnt"]
        data_tmp["ts_code"] = ts_code
        data_lst.append(data_tmp)
    except:
        print(ts_code)

In [16]:
stock_comment_detail_scrd_focus_em_df.columns = ["trade_date", "follow_user_cnt"]

In [17]:
stock_comment_detail_scrd_focus_em_df["ts_code"] = code_add_suffix("688653")

In [26]:
df_f = pd.merge(df, stock_comment_detail_scrd_focus_em_df, on = ["trade_date", "ts_code"])

In [27]:
df_f.head(100)

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,follow_user_cnt
0,688653.SH,2025-05-29,11.27,11.63,11.27,11.63,11.28,0.35,3.1028,58217.1,66912.5,60.8
1,688653.SH,2025-05-28,11.52,11.55,11.21,11.28,11.46,-0.18,-1.5707,33472.1,37926.0,60.8
2,688653.SH,2025-05-27,11.66,11.66,11.36,11.46,11.50,-0.04,-0.3478,32929.8,37627.9,61.2
3,688653.SH,2025-05-26,11.31,11.51,11.31,11.50,11.32,0.18,1.5901,29112.3,33256.8,62.0
4,688653.SH,2025-05-23,11.57,11.62,11.32,11.32,11.65,-0.33,-2.8326,47777.4,54775.6,61.6
5,688653.SH,2025-05-22,11.45,12.04,11.43,11.65,11.53,0.12,1.0408,63618.4,75036.2,60.4
6,688653.SH,2025-05-21,11.73,11.73,11.44,11.53,11.66,-0.13,-1.1149,33788.2,39014.6,60.4
7,688653.SH,2025-05-20,11.45,11.66,11.38,11.66,11.45,0.21,1.8341,39839.6,46021.5,60.4
8,688653.SH,2025-05-19,11.49,11.54,11.32,11.45,11.40,0.05,0.4386,35026.8,40034.0,61.2
9,688653.SH,2025-05-16,11.38,11.54,11.32,11.40,11.38,0.02,0.1757,32846.4,37614.4,60.0
10,688653.SH,2025-05-15,11.55,11.69,11.35,11.38,11.64,-0.26,-2.2337,41265.5,47266.8,60.0
11,688653.SH,2025-05-14,11.81,11.85,11.53,11.64,11.75,-0.11,-0.9362,54292.8,63298.3,60.8
12,688653.SH,2025-05-13,11.64,12.07,11.64,11.75,11.69,0.06,0.5133,86689.5,102756.0,60.0
13,688653.SH,2025-05-12,11.50,11.80,11.44,11.69,11.39,0.30,2.6339,66612.7,77482.9,61.2
14,688653.SH,2025-05-09,11.86,11.90,11.38,11.39,11.90,-0.51,-4.2857,64042.3,73909.6,61.2
15,688653.SH,2025-05-08,11.75,11.95,11.66,11.90,11.74,0.16,1.3629,59796.7,70639.4,61.2
16,688653.SH,2025-05-07,11.88,12.04,11.59,11.74,11.80,-0.06,-0.5085,78729.6,92642.3,62.0
17,688653.SH,2025-05-06,11.65,11.83,11.58,11.80,11.50,0.30,2.6087,42680.2,50082.7,62.4
18,688653.SH,2025-04-30,11.35,11.65,11.35,11.50,11.35,0.15,1.3216,42965.8,49681.1,60.4
19,688653.SH,2025-04-29,11.19,11.42,11.09,11.35,11.19,0.16,1.4298,28764.1,32558.2,60.4
20,688653.SH,2025-04-28,11.48,11.48,11.15,11.19,11.45,-0.26,-2.2707,27736.9,31312.0,60.8
21,688653.SH,2025-04-25,11.42,11.59,11.40,11.45,11.51,-0.06,-0.5213,21326.1,24557.1,59.6
22,688653.SH,2025-04-24,11.78,11.78,11.37,11.51,11.75,-0.24,-2.0426,47076.0,54222.4,59.6
23,688653.SH,2025-04-23,11.80,12.00,11.62,11.75,11.77,-0.02,-0.1699,32895.1,38717.9,61.6
24,688653.SH,2025-04-22,11.84,11.96,11.62,11.77,11.91,-0.14,-1.1755,54978.9,64689.4,61.6
25,688653.SH,2025-04-21,12.03,12.22,11.85,11.91,12.01,-0.10,-0.8326,55491.8,66522.9,62.4
26,688653.SH,2025-04-18,12.41,12.41,11.91,12.01,12.39,-0.38,-3.0670,51200.8,61676.4,63.2
27,688653.SH,2025-04-17,12.01,12.79,11.97,12.39,12.14,0.25,2.0593,91835.4,114332.0,62.8
28,688653.SH,2025-04-16,11.68,12.50,11.60,12.14,11.56,0.58,5.0173,136377.0,165864.0,60.0

In [28]:
lag_cols = []
for lag_col in ["vol", "amount", "follow_user_cnt"]:
    lag_cols.append(f"{lag_col}_lag1")
    df_f[f"{lag_col}_lag1"] = df_f[lag_col].shift(1)

In [29]:
df_f.head(2)

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,follow_user_cnt,vol_lag1,amount_lag1,follow_user_cnt_lag1
0,688653.SH,2025-05-29,11.27,11.63,11.27,11.63,11.28,0.35,3.1028,58217.1,66912.5,60.8,NaN,NaN,NaN
1,688653.SH,2025-05-28,11.52,11.55,11.21,11.28,11.46,-0.18,-1.5707,33472.1,37926.0,60.8,58217.1,66912.5,60.8

In [30]:
df_f.dropna(subset=['pct_chg'] + lag_cols)[['pct_chg'] + lag_cols].corr()

                       pct_chg  vol_lag1  amount_lag1  follow_user_cnt_lag1
pct_chg               1.000000  0.439348     0.453442              0.266955
vol_lag1              0.439348  1.000000     0.998496              0.309157
amount_lag1           0.453442  0.998496     1.000000              0.332872
follow_user_cnt_lag1  0.266955  0.309157     0.332872              1.000000